#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2012 SjB <steve@nca.uwo.ca>. All Rights Reserved.

srcs = [
    'Program.cs'
]

external_libs = [
    'Eto',
    'Eto.Platform'
]

[bld.read_assembly(x, install_path = bld.env.default_app_install_path) for x in external_libs]

uselib = ['NCA.CavraDriver']
uselib.extend(external_libs)

bld(
    features = 'cs cs_dev',
    source = srcs,
    install_path = bld.env.default_app_install_path,
    gen = '{0}.exe'.format(bld.env.APPNAME),
    type = 'exe',
    use = uselib
)
