#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2012 SjB <steve@nca.uwo.ca>. All Rights Reserved.

dll_name = 'NCA.CavraDriver'

srcs = [
    'AssemblyInfo.cs',
    'IAttenuator.cs',
    'Cavra.cs'
]

external_libs = [
    'SjB.Hid'
]

[bld.read_assembly(x, install_path = bld.env.default_app_install_path) for x in external_libs]

uselib = []
uselib.extend(external_libs)

bld(
    features = 'cs',
    source = srcs,
    install_path = bld.env.default_app_install_path,
    gen = '{0}.dll'.format(dll_name),
    name = dll_name,
    type = 'library',
    use = uselib
)
